### ISSUE TITLE
打包后 大文件可以上传但是小文件上传不了

### ISSUE THREAD

**Issue by notbucai** [tencentyun/cos-xml-react-native#4]
大文件可以上传但是小文件上传一点后就卡住了

**Comment by notbucai** [comment]
项目打包后 小于1m（左右）的图片上传后没有成功的回调

**Comment by notbucai** [comment]
![image](https://user-images.githubusercontent.com/32786133/102709515-54599380-42e6-11eb-88af-64eb40cf7ff9.png)
![image](https://user-images.githubusercontent.com/32786133/102709516-591e4780-42e6-11eb-9543-2ed8159c28ef.png)
看日志已经上传完成了，但是不给回调

**Comment by notbucai** [comment]
![Uploading image.png…]()

**Comment by notbucai** [comment]
![image](https://user-images.githubusercontent.com/32786133/102709734-edd57500-42e7-11eb-95e9-dcce02af991e.png)

**Comment by notbucai** [comment]
有空的话希望能支援一下

**Comment by konakonall** [comment]
@notbucai  我这里测试倒是没问题的，

[Mon Dec 28 2020 17:24:46.877]  LOG      put Progress callback :  5361 5361
[Mon Dec 28 2020 17:24:47.200]  LOG      {"Bucket": "dotnet-ut-obj-1253653367", "ETag": "\"584613416caa2de26ae39523aa47403e\"", "Key": "rn-example-object", "Location": "https://dotnet-ut-obj-1253653367.cos.ap-guangzhou.myqcloud.com/rn-example-object"}

**Comment by notbucai** [comment]
已经换了一个方案了，自己封装了一个基于rn XMLHttpRequest 的了

**Comment by jerloo** [comment]
升级对应的qcloud-sdk-android到最新版本可以解决这个问题

我目前在使用5.6.1可以正常上传了
